export type Block = { type: "p" | "h2"; text: string }

export type Post = {
  title: string
  slug: string
  date: string
  year: number
  excerpt: string
  reading: string
  cover_url?: string | null
  image_urls?: string[] | null
  href?: string
  body?: Block[]
}

export const posts: Post[] = [
  {
    title: "I Brought Raycast to Ethiopia",
    slug: "i-brought-raycast-to-ethiopia",
    date: "Aug 8",
    year: 2026,
    reading: "4 min read",
    cover_url: "https://fmegvzwxqrhkhktnaukr.supabase.co/storage/v1/object/public/post-covers/0346798c-54d3-4f3b-be05-4cc4deeb13bf/1787217343132-86ovsa.jpg",
    image_urls: [
      "https://fmegvzwxqrhkhktnaukr.supabase.co/storage/v1/object/public/post-covers/0346798c-54d3-4f3b-be05-4cc4deeb13bf/1787217343132-86ovsa.jpg",
      "https://fmegvzwxqrhkhktnaukr.supabase.co/storage/v1/object/public/post-covers/0346798c-54d3-4f3b-be05-4cc4deeb13bf/1787217343432-t99x9i.jpg"
    ],
    excerpt: "August 8, 2026 \u00b7 Addis Ababa, Ethiopia. Notes on hosting the first official Raycast meetup in Ethiopia.",
    body: [
      { type: "p", text: "Aug 8" },
      { type: "p", text: "It started with a simple thought: \u201cWhy don\u2019t we bring Raycast to Ethiopia?\u201d At first, it was just an idea, but I eventually decided to stop thinking about it and actually make it happen." },
      { type: "p", text: "As a Raycast Ambassador, I organized and hosted the first Raycast Meetup in Ethiopia. And honestly, this became one of the most meaningful community projects I\u2019ve worked on so far. There was a lot happening behind the scenes that people never really see \u2014 finding and securing the venue, working with partners, planning the experience, handling logistics, promoting the event, communicating with the community, and dealing with all the little problems that came along the way." },
      { type: "p", text: "Then I started watching the registrations grow. First it was a few people, then dozens, and eventually we passed 200+ registrations. Seeing that number was crazy because it showed me that people were actually interested in coming together and being part of something I had started as just an idea." },
      { type: "p", text: "Then August 8th finally came." },
      { type: "p", text: "After weeks of planning, I walked into the venue and saw 80+ people actually there. That moment hit differently. I knew how much work had gone into getting to that point. Every message, every plan, every last-minute change, and every small problem had led to that room." },
      { type: "p", text: "Something that started in my head was now happening in real life." },
      { type: "p", text: "People were meeting each other, learning, trying Raycast, sharing ideas, and enjoying the experience. Seeing that made all the work worth it." },
      { type: "p", text: "But what I got from this wasn&#x27;t just another event to put on my resume. I learned how to take an idea and turn it into something real. I learned how to work with a global company while creating something for my local community, and I learned a lot about planning, partnerships, logistics, communication, and community building." },
      { type: "p", text: "Most importantly, I gained confidence in myself." },
      { type: "p", text: "I realized I don&#x27;t always have to wait for someone else to create the opportunity I want to see. Sometimes, I can just create it myself." },
      { type: "p", text: "200+ people registered . 80+ showed up. And I made it happen." },
      { type: "p", text: "It wasn&#x27;t perfect, and there are definitely things I&#x27;d do differently next time. But that&#x27;s what makes the experience mine. I planned it, organized it, promoted it, handled the problems, and brought the community together." },
      { type: "p", text: "For me, the Raycast Meetup was more than just an event. It was proof that I can take an idea, put in the work, and turn it into something real." },
      { type: "p", text: "And honestly, I feel like this is only the beginning. \ud83d\udda4" },
    ],
  },
  {
    title: "Building the Raycast Community in Addis Ababa",
    slug: "building-the-raycast-community-in-addis-ababa",
    date: "Jun 17",
    year: 2026,
    reading: "5 min read",
    cover_url: "https://fmegvzwxqrhkhktnaukr.supabase.co/storage/v1/object/public/post-covers/0346798c-54d3-4f3b-be05-4cc4deeb13bf/1781965376122-kprpq8.jpg",
    image_urls: ["https://fmegvzwxqrhkhktnaukr.supabase.co/storage/v1/object/public/post-covers/0346798c-54d3-4f3b-be05-4cc4deeb13bf/1781965376122-kprpq8.jpg"],
    excerpt: "A new chapter in my journey as a builder becoming part of the Raycast Ambassador community.",
    body: [
      { type: "p", text: "A new chapter in my journey as a builder becoming part of the Raycast Ambassador community" },
      { type: "p", text: "A new chapter in my journey as a builder becoming part of the Raycast Ambassador community." },
      { type: "p", text: "Recently, I had the opportunity to connect with Stephanie Leong, Raycast\u2019s Community Manager, and officially become a Raycast Ambassador." },
      { type: "p", text: "But for me, this is not just about a title." },
      { type: "p", text: "It\u2019s about community.\nI\u2019ve always believed that great things happen when builders come together, share knowledge, and create spaces where people can learn from each other." },
      { type: "p", text: "Through this opportunity, I\u2019m looking forward to bringing more conversations, events, and meetups around developer tools, productivity, and building with technology." },
      { type: "p", text: "Seeing global communities grow has always inspired me, and now I have the chance to contribute by helping create more connections between local builders and the wider ecosystem." },
      { type: "p", text: "This is just the beginning." },
      { type: "p", text: "More events, more conversations, and more things to build." },
    ],
  },
  {
    title: "v0 IRL Addis Ababa \u2013 My first event",
    slug: "v0-irl-addis-ababa-prompt-to-production-2026-recap",
    date: "Feb 7",
    year: 2026,
    reading: "7 min read",
    cover_url: "https://fmegvzwxqrhkhktnaukr.supabase.co/storage/v1/object/public/post-covers/0346798c-54d3-4f3b-be05-4cc4deeb13bf/1779875577700-u6v99h.jpg",
    image_urls: ["https://fmegvzwxqrhkhktnaukr.supabase.co/storage/v1/object/public/post-covers/0346798c-54d3-4f3b-be05-4cc4deeb13bf/1779875577700-u6v99h.jpg"],
    excerpt: "Hosting one of the global v0 IRL events in Addis Ababa taught me what it really takes to run a builder-focused event \u2014 from execution and communication to community impact and unexpected challenges.",
    body: [
      { type: "p", text: "Feb 7" },
      { type: "p", text: "Hosting one of the global v0 IRL events in Addis Ababa taught me what it really takes to run a builder-focused event \u2014 from execution and communication to community impact and unexpected challenges." },
      { type: "p", text: "On February 7, I had the opportunity to host v0 IRL \u2013 Addis Ababa, part of the global Prompt to Production 2026 series that brought together over 5,000 builders across 60+ events in 28 countries. The goal was simple but powerful: help builders turn ideas into real, production-ready projects through fast execution, collaboration, and creativity." },
      { type: "p", text: "Organizing events is harder than it looks" },
      { type: "p", text: "Before hosting this event, I honestly underestimated how much work goes into organizing something like this. As an attendee, you only see the surface \u2014 the talks, the energy, the final results." },
      { type: "p", text: "But behind the scenes, it\u2019s a completely different world. From coordinating logistics, managing timelines, handling unexpected issues, and making sure participants have a smooth experience, there\u2019s always something happening. It gave me a new level of respect for every event organizer I\u2019ve ever seen." },
      { type: "p", text: "Communication and coordination matter more than anything" },
      { type: "p", text: "One of the biggest lessons I learned was how important clear communication is. Whether it was working with participants, understanding the flow of the event, or aligning with the broader v0 structure, everything depended on how well information was shared and understood." },
      { type: "p", text: "Small miscommunication can easily scale into bigger issues in live events, so being clear, calm, and responsive became very important throughout the process." },
      { type: "p", text: "Building a community is the real win!" },
      { type: "p", text: "Beyond the projects and outcomes, the most valuable part was seeing builders come together in one space. People were not just building they were learning, helping each other, and sharing ideas." },
      { type: "p", text: "It made me realize that the real impact of events like this is not just the final winners, but the connections and motivation people leave with." },
      { type: "p", text: "Two winning projects from Addis Ababa" },
      { type: "p", text: "After community voting and review by the v0 team, two participants from the Addis Ababa event were selected as winners. This moment highlighted the strength of the local builder community and showed that talent from Ethiopia can compete on a global stage." },
      { type: "p", text: "Final reflection" },
      { type: "p", text: "This experience taught me that organizing events is not just about execution - it\u2019s about adaptability, patience, and problem-solving in real time." },
      { type: "p", text: "Not everything goes as planned, and that\u2019s okay. The most important part is learning how to adjust, support people, and keep things moving forward." },
      { type: "p", text: "I\u2019m grateful for the experience and excited to continue building more spaces where people can learn, create, and grow together." },
    ],
  },
  {
    title: "Zero to Agents Addis Ababa - My Second Event, Global Winners, and the Power of Local Builders",
    slug: "zero-to-agents-addis-ababa-my-second-event-global-winners-and-the-power-of-local-builders",
    date: "May 2",
    year: 2026,
    reading: "9 min read",
    cover_url: "https://fmegvzwxqrhkhktnaukr.supabase.co/storage/v1/object/public/post-covers/0346798c-54d3-4f3b-be05-4cc4deeb13bf/1779881656438-bdfq5z.jpg",
    image_urls: ["https://fmegvzwxqrhkhktnaukr.supabase.co/storage/v1/object/public/post-covers/0346798c-54d3-4f3b-be05-4cc4deeb13bf/1779881656438-bdfq5z.jpg"],
    excerpt: "Hosted in May 2026, Zero to Agents Addis Ababa started as a small community-driven builder event in collaboration with Vercel. It ended with participants from the local event placing #1 and #2 globally among nearly 8,000 builders across 40+ countries proving that local communities can create global impact.",
    body: [
      { type: "p", text: "May 2" },
      { type: "p", text: "Hosted in May 2026, Zero to Agents Addis Ababa started as a small community-driven builder event in collaboration with Vercel. It ended with participants from the local event placing #1 and #2 globally among nearly 8,000 builders across 40+ countries proving that local communities can create global impact." },
      { type: "p", text: "A few weeks ago, in May 2 2026, I hosted Zero to Agents Addis Ababa in collaboration with Vercel and honestly, I didn\u2019t expect my second event ever to turn into something this big." },
      { type: "p", text: "What started as a local builder event around AI agents and modern tools eventually led to participants from Addis Ababa placing #1 and #2 globally in the hackathon." },
      { type: "p", text: "Even now, it still feels unreal to say that." },
      { type: "p", text: "Starting with an idea\nThe goal of the event was simple: Bring together builders, students, developers, and curious people who wanted to experiment with AI agents and actually build things." },
      { type: "p", text: "I\u2019ve always believed there are many talented builders locally who just need the right environment, community, and opportunity to showcase what they can do." },
      { type: "p", text: "So I started organizing." },
      { type: "p", text: "I used my community channels, shared announcements online, invited people from different builder spaces, and slowly the event started gaining momentum." },
      { type: "p", text: "For me, the most exciting part wasn\u2019t just hosting the event \u2014 it was seeing people genuinely interested in creating real projects." },
      { type: "p", text: "Not just consuming AI content.\nNot just watching trends.\nActually building." },
      { type: "p", text: "Hosting is harder than it looks" },
      { type: "p", text: "Since this was only my second event, I learned very quickly how much work happens behind the scenes." },
      { type: "p", text: "As attendees, people usually only see the exciting part:\nthe talks, projects, demos, and final results." },
      { type: "p", text: "But organizing an event means constantly solving problems in real time." },
      { type: "p", text: "Managing communication, helping participants, coordinating schedules, answering questions, handling unexpected issues, and keeping the energy alive throughout the event became a huge learning experience for me." },
      { type: "p", text: "There were stressful moments.\nThings didn\u2019t always go exactly as planned.\nBut honestly, that\u2019s what made the experience valuable." },
      { type: "p", text: "It taught me adaptability, patience, and how important community management really is." },
      { type: "p", text: "Watching builders grow in real time" },
      { type: "p", text: "One of the best parts of the event was seeing how quickly people evolved once they started building together." },
      { type: "p", text: "Some participants joined with only rough ideas.\nSome had never worked with AI agents before.\nOthers simply came to explore and learn." },
      { type: "p", text: "But as the event continued, people started collaborating, helping each other, sharing ideas, debugging projects together, and pushing their builds further." },
      { type: "p", text: "The atmosphere slowly became more than just a hackathon." },
      { type: "p", text: "It became a real builder environment." },
      { type: "p", text: "The moment everything changed" },
      { type: "p", text: "Then came the final announcement." },
      { type: "p", text: "Out of nearly 8,000 builders across 40+ countries, projects from our Addis Ababa event placed #1 and #2 globally." },
      { type: "p", text: "That moment honestly changed how I see local community events." },
      { type: "p", text: "Seeing builders from Ethiopia compete \u2014 and win \u2014 on a global stage was incredibly inspiring." },
      { type: "p", text: "It proved that talent exists everywhere.\nPeople just need access, exposure, and opportunities." },
      { type: "p", text: "Final reflection" },
      { type: "p", text: "Hosting Zero to Agents Addis Ababa taught me that community building is not just about gathering people in one room." },
      { type: "p", text: "It\u2019s about creating momentum, encouraging people to experiment, and building spaces where others feel motivated to create." },
      { type: "p", text: "For my second event ever, this experience taught me more than I expected about leadership, execution, communication, and the power of local builder communities." },
      { type: "p", text: "Huge appreciation to everyone who joined, built, supported, and helped make the event possible." },
      { type: "p", text: "This is only the beginning." },
    ],
  },
  {
    title: "How Zero to Agents Put Ethiopia on the Vercel Community Map",
    slug: "how-zero-to-agents-put-ethiopia-on-the-vercel-community-map",
    date: "May 2",
    year: 2026,
    reading: "6 min read",
    cover_url: "https://fmegvzwxqrhkhktnaukr.supabase.co/storage/v1/object/public/post-covers/0346798c-54d3-4f3b-be05-4cc4deeb13bf/1779883278897-58ikhs.png",
    image_urls: ["https://fmegvzwxqrhkhktnaukr.supabase.co/storage/v1/object/public/post-covers/0346798c-54d3-4f3b-be05-4cc4deeb13bf/1779883278897-58ikhs.png"],
    excerpt: "Ethiopia was officially represented on the Vercel community map through Zero to Agents Addis Ababa in May 2026 \u2014 marking the first time a local builder event connected our community to a global ecosystem.",
    body: [
      { type: "p", text: "May 2" },
      { type: "p", text: "Ethiopia was officially represented on the Vercel community map through Zero to Agents Addis Ababa in May 2026 \u2014 marking the first time a local builder event connected our community to a global ecosystem." },
      { type: "p", text: "In May 2026, I hosted Zero to Agents Addis Ababa in collaboration with Vercel as part of the global build week and one of the most meaningful outcomes of the event was that Ethiopia got officially represented on the Vercel community map." },
      { type: "p", text: "This wasn\u2019t just about hosting a meetup." },
      { type: "p", text: "It was about visibility." },
      { type: "p", text: "For a long time, I used to see global builder communities and events happening in other countries, while Ethiopia was rarely shown on those kinds of global maps or ecosystems. So seeing Addis Ababa appear as part of the Vercel community network through this event felt like a real milestone." },
      { type: "p", text: "What made it even more special is that it didn\u2019t happen by chance it happened through a local builder event I organized. Through Zero to Agents, we were able to connect Ethiopian builders to a global ecosystem and officially put our community on the map." },
      { type: "p", text: "For me, it felt like a moment of representation showing that there are active builders here, people experimenting with AI, and a growing community that deserves global visibility." },
      { type: "p", text: "Even more importantly, it showed that representation doesn\u2019t always start with big institutions. Sometimes it starts with one community event, a few motivated builders, and the decision to just bring people together and build." },
      { type: "p", text: "It also gave people in the local scene a sense of belonging that they are part of something global, not separate from it." },
      { type: "p", text: "It\u2019s a small step in terms of a single event, but a meaningful one for local builder presence in global tech spaces." },
      { type: "p", text: "And honestly, it feels like just the beginning." },
    ],
  },
]
